### ISSUE TITLE
Add support for MySQL, MariaDB and Percona Server for MySQL

### ISSUE THREAD

**Issue by marclaporte** [bingo-soft/jabe#3]
[Please, pay attention that at the moment it supports only Postgresql (in future I plan to support other databases as well).](https://github.com/bingo-soft/jabe/issues/2#issuecomment-1554210637)

**Comment by bingo-soft** [comment]
@marclaporte Hi, Marc! In fact it requires some testing of [MyBatis](https://github.com/bingo-soft/mybatis) library, which incapsulates all database activity. When I have some time, I'll do that. Though, I wish someone could contribute

**Comment by bingo-soft** [comment]
I'm closing this issue, since new release supports MySQL and its forks. Please, check it out!
